version: 2.1

executors:
  common-executor:
    working_directory: ~/go/src/github.com/Clever/breakdown
    docker:
      - image: cimg/go:1.19
    resource_class: small

jobs:
  build:
    executor: common-executor
    steps:
      - attach_workspace:
          at: ~/go/src/github.com/Clever
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker buildx create --name container --driver=docker-container --use --bootstrap
      - run: docker buildx build --load -t image:base --target builder --builder container .
      - run: docker buildx build --load -t image:latest --builder container .

workflows:
  version: 2.1
  build:
    jobs:
      - build
